apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  labels:
    app: mysql-rc
spec:
  replicas: 1
  selector:
    app: mysql-rc
  template:
    metadata:
      labels:
        app: mysql-rc
    spec:
      containers:
      -
        env:
          - 
            name: MYSQL_ROOT_PASSWORD
            value: root
        image: mysql:5.5
        name: mysql-rc
        ports:
          - 
            containerPort: 3306
        volumeMounts:
          - 
            mountPath: /var/lib/mysql
            name: mysql-storage
      volumes:
        - 
          hostPath:
            #path: /usr/src/apps/iamyourcoder/production/volumes/mysql/5.5
            path: /home/dsantos/Dell/Dev/Projects/iamyourcoder/volumes/mysql/5.5
          name: mysql-storage