apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-production-svc
  name: nginx-production-svc
spec:
  ports:
    - 
      port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  clusterIP: 10.0.0.40
  selector:
    app: nginx-production-rc