apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  labels:
    app: redis-rc
spec:
  replicas: 1
  selector:
    app: redis-rc
  template:
    metadata:
      labels:
        app: redis-rc
    spec:
      containers:
      -
        image: redis:3.2-alpine
        name: redis-rc
        ports:
          - 
            containerPort: 6379