apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-rc
spec:
  replicas: 2
  selector:
    app: nginx-rc
  template:
    metadata:
      labels:
        app: nginx-rc
    spec:
      containers:
      -
        image: delermando/nginx-django:1.1
        name: nginx-rc
        ports:
          - 
            containerPort: 80
        command: ["/usr/local/bin/entrypoint.sh"]
        volumeMounts:
          -
            mountPath: /etc/nginx/sites-enabled
            name: sites-enabled
          -
            mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
          -
            mountPath: /usr/src/app
            name: app-src
          -
            mountPath: /usr/local/bin/entrypoint.sh
            name: entrypoint
          -
            mountPath: /etc/uwsgi
            name: uwsgi-conf
      volumes:
        -
          hostPath:
            path: #path do projeto (pwd)  /config/nginx/sites-enabled
          name: sites-enabled
        -
          hostPath:
            path: #path do projeto (pwd)  /config/nginx/server/nginx.conf
          name: nginx-conf
        -
          hostPath:
            path: #path do projeto (pwd)  /src
          name: app-src
        -
          hostPath:
            path: #path do projeto (pwd)  /config/kubernetes/nginx/entrypoint.sh
          name: entrypoint
        -
          hostPath:
            path: #path do projeto (pwd)  /config/uwsgi
          name: uwsgi-conf
